# Generated by Django 3.2.8 on 2021-11-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=100, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='uploads/categories/img', verbose_name='Imagen')),
                ('fechaCreada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('categoriaPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.categoria', verbose_name='Categoria perteneciente')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='uploads/lessons/img')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('aprobacion', models.BooleanField(default=False, verbose_name='Aprobación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.categoria', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('link', models.CharField(max_length=500)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante_Lecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.SmallIntegerField(verbose_name='Orden de aparición')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('path', models.FileField(upload_to='uploads/files', verbose_name='Archivo')),
                ('lipo', models.CharField(choices=[('PDF', 'Archivo PDF'), ('IMG', 'Imagen'), ('DOC', 'Archivo Word'), ('PPX', 'PowerPoint'), ('XLX', 'Archivo Excel'), ('ANY', 'Archivo')], max_length=3, verbose_name='Tipo de archivo')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.leccion')),
            ],
        ),
    ]
