# Generated by Django 3.2.8 on 2021-11-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0003_rename_estudiante_leccion_estudiante_leccione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='orden',
            field=models.PositiveSmallIntegerField(verbose_name='Orden de aparición'),
        ),
    ]
