# Generated by Django 3.2.13 on 2022-05-14 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('LearningCatalog', '0004_alter_archivo_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(max_length=500, verbose_name='Descripción_pregunta')),
                ('respuesta', models.IntegerField()),
                ('opinion', models.TextField(max_length=500, verbose_name='Opinion')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante_Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.encuesta')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
            ],
        ),
    ]
