# Generated by Django 3.2.13 on 2022-05-14 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('LearningCatalog', '0005_encuesta_estudiante_encuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante_Encuesta_Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.encuesta')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.leccion')),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante_Encuesta',
        ),
    ]
