# Generated by Django 3.2.13 on 2022-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0006_auto_20220513_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.TextField(max_length=500, verbose_name='Descripción_pregunta')),
                ('imagen', models.ImageField(upload_to='uploads/categories/img', verbose_name='Imagen')),
                ('respuesta', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante_encuesta_leccion',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='estudiante_encuesta_leccion',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='Encuesta',
        ),
    ]
