# Generated by Django 3.2.13 on 2022-05-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0008_auto_20220516_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leccion_Ejercicio',
        ),
    ]
