# Generated by Django 3.2.13 on 2022-05-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0009_delete_leccion_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='leccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.leccion', verbose_name='A que leccion pertenece'),
            preserve_default=False,
        ),
    ]
