# Generated by Django 3.2.13 on 2022-05-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0005_auto_20220516_1531'),
        ('LearningCatalog', '0010_ejercicio_leccion'),
    ]

    operations = [
    ]
