# Generated by Django 3.2.12 on 2022-05-26 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('LearningCatalog', '0011_merge_0005_auto_20220516_1531_0010_ejercicio_leccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='LearningCatalog.leccion')),
            ],
        ),
    ]
