# Generated by Django 3.2.12 on 2022-05-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('LearningCatalog', '0012_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='likes',
            field=models.ManyToManyField(related_name='lesson_posts', to='accounts.Estudiante'),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
