# Generated by Django 3.2.12 on 2022-05-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0014_solicitar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitar',
            name='user',
            field=models.TextField(max_length=500),
        ),
    ]
