# Generated by Django 3.2.12 on 2022-05-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('LearningCatalog', '0015_alter_solicitar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leccion',
            name='likes',
        ),
        migrations.AddField(
            model_name='leccion',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to='accounts.Estudiante'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.leccion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
            ],
        ),
    ]
