# Generated by Django 3.2.13 on 2022-06-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0018_auto_20220605_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='exercises',
            field=models.ManyToManyField(to='LearningCatalog.Exercises'),
        ),
    ]
