# Generated by Django 3.2.13 on 2022-06-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0019_leccion_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='questions',
            field=models.ManyToManyField(to='LearningCatalog.QuestionExercise'),
        ),
        migrations.AlterField(
            model_name='questionexercise',
            name='answers',
            field=models.ManyToManyField(to='LearningCatalog.AnswerExercise'),
        ),
    ]
