# Generated by Django 3.2.13 on 2022-06-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0020_auto_20220605_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptexercise',
            name='attempter',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='allowed_attempts',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='time_limit_mins',
        ),
    ]
