# Generated by Django 3.2.13 on 2022-06-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0021_auto_20220605_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerexercise',
            old_name='answer_text',
            new_name='answer_text_exercise',
        ),
        migrations.RenameField(
            model_name='answerexercise',
            old_name='is_correct',
            new_name='is_correct_exercise',
        ),
        migrations.RenameField(
            model_name='attempterexercise',
            old_name='completed',
            new_name='completed_exercise',
        ),
        migrations.RenameField(
            model_name='attempterexercise',
            old_name='score',
            new_name='score_exercise',
        ),
        migrations.RenameField(
            model_name='exercises',
            old_name='date',
            new_name='date_exercise',
        ),
        migrations.RenameField(
            model_name='exercises',
            old_name='description',
            new_name='description_exercise',
        ),
        migrations.RenameField(
            model_name='exercises',
            old_name='due',
            new_name='due_exercise',
        ),
        migrations.RenameField(
            model_name='exercises',
            old_name='questions',
            new_name='questions_exercise',
        ),
        migrations.RenameField(
            model_name='exercises',
            old_name='title',
            new_name='title_exercise',
        ),
        migrations.RenameField(
            model_name='questionexercise',
            old_name='answers',
            new_name='answers_exercise',
        ),
        migrations.RenameField(
            model_name='questionexercise',
            old_name='points',
            new_name='points_exercise',
        ),
        migrations.RenameField(
            model_name='questionexercise',
            old_name='question_text',
            new_name='question_text_exercise',
        ),
    ]
