# Generated by Django 3.2.13 on 2022-06-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0023_auto_20220607_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='leccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.leccion'),
            preserve_default=False,
        ),
    ]
