# Generated by Django 3.2.13 on 2022-06-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0024_encuesta_leccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='leccion',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='id_leccion',
            field=models.IntegerField(null=True),
        ),
    ]
