# Generated by Django 3.2.13 on 2022-06-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0025_auto_20220608_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='id_leccion',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='leccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.leccion'),
        ),
    ]
