# Generated by Django 3.2.13 on 2022-06-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0026_auto_20220608_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='leccion',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='id_leccion',
            field=models.IntegerField(null=True),
        ),
    ]
