# Generated by Django 3.2.8 on 2021-11-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('foto', models.ImageField(upload_to='uploads/people/img', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='SobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('foto', models.ImageField(upload_to='uploads/sobreNosotros/img', verbose_name='Foto')),
            ],
        ),
    ]
