# Generated by Django 3.2.8 on 2021-11-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sobrenosotros',
            options={'verbose_name': 'Sección Sobre Nosotros', 'verbose_name_plural': 'Sección Sobre Nosotros'},
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='descripcion',
            field=models.TextField(max_length=250, verbose_name='Descripción'),
        ),
    ]
