# Generated by Django 3.2.8 on 2021-11-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_auto_20211123_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='descripcion',
            field=models.TextField(max_length=250, verbose_name='Descripción'),
        ),
    ]
