# Generated by Django 3.2.8 on 2021-11-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0003_alter_persona_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrenosotros',
            name='descripcion',
            field=models.TextField(max_length=1000, verbose_name='Descripción'),
        ),
    ]
