# Generated by Django 3.2.12 on 2022-05-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
