# Generated by Django 3.2.8 on 2021-11-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen1', models.ImageField(upload_to='uploads/carrousel/img', verbose_name='Imagen 3')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenLecciones', models.ImageField(upload_to='uploads/homeSection/img', verbose_name='Imagen de lecciones')),
                ('textoLecciones', models.TextField(max_length=250, verbose_name='Texto de lecciones')),
                ('imagenCategorias', models.ImageField(upload_to='uploads/homeSection/img', verbose_name='Imagen de categorías')),
                ('textoCategorias', models.TextField(max_length=250, verbose_name='Texto de categorías')),
                ('imagenCrearCuenta', models.ImageField(upload_to='uploads/homeSection/img', verbose_name='Imagen de crear cuenta')),
                ('textoCrearCuenta', models.TextField(max_length=250, verbose_name='Texto de crear cuenta')),
            ],
        ),
    ]
