# Generated by Django 3.2.8 on 2021-11-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrousel',
            options={'verbose_name': 'Carrousel', 'verbose_name_plural': 'Carrouseles'},
        ),
        migrations.AlterModelOptions(
            name='homesections',
            options={'verbose_name': 'Seccion de inicio', 'verbose_name_plural': 'Seccion de inicio'},
        ),
        migrations.AddField(
            model_name='carrousel',
            name='imagen2',
            field=models.ImageField(default=None, upload_to='uploads/carrousel/img', verbose_name='Imagen 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrousel',
            name='imagen3',
            field=models.ImageField(default=None, upload_to='uploads/carrousel/img', verbose_name='Imagen 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='imagen1',
            field=models.ImageField(upload_to='uploads/carrousel/img', verbose_name='Imagen 1'),
        ),
    ]
