# Generated by Django 3.2.8 on 2021-11-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_auto_20211119_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumboTronHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=250, verbose_name='Título')),
                ('subtitulo', models.TextField(max_length=250, verbose_name='Subtítulo')),
                ('subtituloPequeno', models.TextField(max_length=250, verbose_name='Subtítulo pequeño')),
            ],
            options={
                'verbose_name': 'Jumbotron',
                'verbose_name_plural': 'Jumbotron',
            },
        ),
    ]
