# Generated by Django 3.2.8 on 2021-11-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_jumbotronhome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesections',
            options={'verbose_name': 'Tarjetas de secciones', 'verbose_name_plural': 'Tarjetas de secciones'},
        ),
    ]
